// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using schoolapp.Infrastructure.Data;

#nullable disable

namespace schoolapp.Infrastructure.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20240930191224_school_settings")]
    partial class school_settings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("school")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DepartmentSupportStaff", b =>
                {
                    b.Property<int>("DepartmentsId")
                        .HasColumnType("integer")
                        .HasColumnName("departments_id");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer")
                        .HasColumnName("staff_id");

                    b.HasKey("DepartmentsId", "StaffId")
                        .HasName("pk_department_support_staff");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("ix_department_support_staff_staff_id");

                    b.ToTable("department_support_staff", "school");
                });

            modelBuilder.Entity("DepartmentTeacher", b =>
                {
                    b.Property<int>("DepartmentsId")
                        .HasColumnType("integer")
                        .HasColumnName("departments_id");

                    b.Property<int>("TeachersId")
                        .HasColumnType("integer")
                        .HasColumnName("teachers_id");

                    b.HasKey("DepartmentsId", "TeachersId")
                        .HasName("pk_department_teacher");

                    b.HasIndex("TeachersId")
                        .HasDatabaseName("ix_department_teacher_teachers_id");

                    b.ToTable("department_teacher", "school");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.ClassGrades.ClassRoom", b =>
                {
                    b.Property<int>("ClassRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("class_room_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassRoomId"));

                    b.Property<string>("ClassroomName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classroom_name");

                    b.Property<int>("GradeId")
                        .HasColumnType("integer")
                        .HasColumnName("grade_id");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("ClassRoomId")
                        .HasName("pk_class_rooms");

                    b.HasIndex("GradeId")
                        .HasDatabaseName("ix_class_rooms_grade_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_class_rooms_school_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_class_rooms_teacher_id");

                    b.ToTable("class_rooms", "school");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.ClassGrades.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_grades");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_grades_school_id");

                    b.ToTable("grades", "school");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.Departments.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentHead")
                        .HasColumnType("integer")
                        .HasColumnName("department_head");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department_name");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.ToTable("departments", "school");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("NationalId")
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<string>("OtherNames")
                        .HasColumnType("text")
                        .HasColumnName("other_names");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Salutation")
                        .HasColumnType("text")
                        .HasColumnName("salutation");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_parents");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_parents_school_id");

                    b.ToTable("parents", "school");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int?>("ClassRoomId")
                        .HasColumnType("integer")
                        .HasColumnName("class_room_id");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("NationalId")
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<string>("OtherNames")
                        .HasColumnType("text")
                        .HasColumnName("other_names");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reg_number");

                    b.Property<string>("Salutation")
                        .HasColumnType("text")
                        .HasColumnName("salutation");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("ClassRoomId")
                        .HasDatabaseName("ix_students_class_room_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_students_school_id");

                    b.ToTable("students", "school");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.StudentParent", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.HasKey("ParentId", "StudentId")
                        .HasName("pk_student_parent");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_student_parent_student_id");

                    b.ToTable("student_parent", "school");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.SupportStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dob");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Designation")
                        .HasColumnType("text")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("NationalId")
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<string>("OtherNames")
                        .HasColumnType("text")
                        .HasColumnName("other_names");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Salutation")
                        .HasColumnType("text")
                        .HasColumnName("salutation");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<string>("StaffNumber")
                        .HasColumnType("text")
                        .HasColumnName("staff_number");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("pk_support_staffs");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_support_staffs_school_id");

                    b.ToTable("support_staffs", "school");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("NationalId")
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<string>("OtherNames")
                        .HasColumnType("text")
                        .HasColumnName("other_names");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("RegNo")
                        .HasColumnType("text")
                        .HasColumnName("reg_no");

                    b.Property<string>("Salutation")
                        .HasColumnType("text")
                        .HasColumnName("salutation");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<string>("TeacherId")
                        .HasColumnType("text")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_teachers");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_teachers_school_id");

                    b.ToTable("teachers", "school");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.School", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchoolId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("HomePage")
                        .HasColumnType("text")
                        .HasColumnName("home_page");

                    b.Property<DateTimeOffset?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by_user_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("schoolname");

                    b.Property<int>("SchoolType")
                        .HasColumnType("integer")
                        .HasColumnName("school_type");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("SchoolId")
                        .HasName("pk_schools");

                    b.ToTable("schools", "school");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.SchoolSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsGroupOfSchools")
                        .HasColumnType("boolean")
                        .HasColumnName("is_group_of_schools");

                    b.Property<int>("ParentSchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_school_id");

                    b.Property<int>("SchoolType")
                        .HasColumnType("integer")
                        .HasColumnName("school_type");

                    b.Property<bool>("UseSingleName")
                        .HasColumnType("boolean")
                        .HasColumnName("use_single_name");

                    b.HasKey("Id")
                        .HasName("pk_school_settings");

                    b.HasIndex("ParentSchoolId")
                        .IsUnique()
                        .HasDatabaseName("ix_school_settings_parent_school_id");

                    b.ToTable("school_settings", "school");
                });

            modelBuilder.Entity("DepartmentSupportStaff", b =>
                {
                    b.HasOne("schoolapp.Domain.Entities.Departments.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_department_support_staff_departments_departments_id");

                    b.HasOne("schoolapp.Domain.Entities.People.SupportStaff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_department_support_staff_support_staffs_staff_id");
                });

            modelBuilder.Entity("DepartmentTeacher", b =>
                {
                    b.HasOne("schoolapp.Domain.Entities.Departments.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_department_teacher_departments_departments_id");

                    b.HasOne("schoolapp.Domain.Entities.People.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_department_teacher_teachers_teachers_id");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.ClassGrades.ClassRoom", b =>
                {
                    b.HasOne("schoolapp.Domain.Entities.ClassGrades.Grade", "Grade")
                        .WithMany("ClassRooms")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_rooms_grades_grade_id");

                    b.HasOne("schoolapp.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_class_rooms_schools_school_id");

                    b.HasOne("schoolapp.Domain.Entities.People.Teacher", "ClassTeacher")
                        .WithMany("ClassRooms")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("fk_class_rooms_teachers_teacher_id");

                    b.Navigation("ClassTeacher");

                    b.Navigation("Grade");

                    b.Navigation("School");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.ClassGrades.Grade", b =>
                {
                    b.HasOne("schoolapp.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grades_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.Parent", b =>
                {
                    b.HasOne("schoolapp.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parents_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.Student", b =>
                {
                    b.HasOne("schoolapp.Domain.Entities.ClassGrades.ClassRoom", "StudentClass")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_students_class_rooms_class_room_id");

                    b.HasOne("schoolapp.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_schools_school_id");

                    b.Navigation("School");

                    b.Navigation("StudentClass");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.StudentParent", b =>
                {
                    b.HasOne("schoolapp.Domain.Entities.People.Parent", null)
                        .WithMany("StudentParents")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_parent_parents_parent_id");

                    b.HasOne("schoolapp.Domain.Entities.People.Student", null)
                        .WithMany("StudentParents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_parent_students_student_id");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.SupportStaff", b =>
                {
                    b.HasOne("schoolapp.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_staffs_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.Teacher", b =>
                {
                    b.HasOne("schoolapp.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_schools_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.SchoolSetting", b =>
                {
                    b.HasOne("schoolapp.Domain.Entities.School", "School")
                        .WithOne("ExtraSettings")
                        .HasForeignKey("schoolapp.Domain.Entities.SchoolSetting", "ParentSchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_school_settings_schools_parent_school_id");

                    b.Navigation("School");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.ClassGrades.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.ClassGrades.Grade", b =>
                {
                    b.Navigation("ClassRooms");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.Parent", b =>
                {
                    b.Navigation("StudentParents");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.Student", b =>
                {
                    b.Navigation("StudentParents");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.People.Teacher", b =>
                {
                    b.Navigation("ClassRooms");
                });

            modelBuilder.Entity("schoolapp.Domain.Entities.School", b =>
                {
                    b.Navigation("ExtraSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
